sudo : required
services:
  - docker

language: generic

before_install:
  - docker build -f Dockerfile.dev -t nishanb/react-dash:latest .

script:
  - docker run -e CI=true nishanb/react-dash:latest npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-dash"
  env: "Reactdash-env"
  bucket_name: "elasticbeanstalk-us-east-2-582459387683"
  bucket_path: "react-dash"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: "$AWS_ACCESS_KEY"