version: "3"
services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "80:3000"
    stdin_open: true
    volumes:
      - /app/node_modules/
      - .:/app
  tests:
    build:
        context: .
        dockerfile: Dockerfile.dev
    stdin_open: true
    volumes:
      - /app/node_modules/
      - .:/app
    command: ["npm", "run", "test"]    